name: Yathit Help
baseurl: /sugar-mobile-app
permalink: /:title.html
product: Yathit Mobile App
gems: 
  - jekyll-assets
  - jekyll-last-modified-at
exclude: [vendor,Gemfile,Gemfile.lock,Rakefile,readme.md]
canonical_domain: https://www.yathit.com
sugarcrm:
  extension_id: iccdnijlhdogaccaiafdpjmbakdcdakk
assets:
  css_compressor: sass
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
